apiVersion: v1
kind: Service
metadata:
  name: stremio
  namespace: stremio
spec:
  ports:
    - name: http
      port: 11470
      targetPort: 11470
      protocol: TCP
    - name: https
      port: 12470
      targetPort: 12470
      protocol: TCP
  selector:
    app: stremio
