apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - authentik
  - blocky
  - capacitor
  - dashboard
  - gitea
  - grafana
  - harbor
  - homarr
  - nextcloud
  - servarr
  - vaultwarden
