apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prometheus
  namespace: prometheus
spec:
  interval: 10m
  chart:
    spec:
      chart: prometheus
      version: 27.41.0
      sourceRef:
        kind: HelmRepository
        name: prometheus
        namespace: prometheus
      interval: 10m
  values:
    server:
      persistentVolume:
        enabled: true
        size: 50Gi
        storageClass: "longhorn-ssd"
      service:
        enabled: true
      baseURL: https://prometheus.seercle.com
      extraFlags:
        - web.enable-lifecycle
        - web.enable-admin-api
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          #nginx.ingress.kubernetes.io/auth-type: basic
          #nginx.ingress.kubernetes.io/auth-secret: prometheus-auth
          #nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
          cert-manager.io/cluster-issuer: "letsencrypt-prod"
          nginx.ingress.kubernetes.io/auth-url: |-
            http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
          nginx.ingress.kubernetes.io/auth-signin: |-
            https://authentik.seercle.com/outpost.goauthentik.io/start?rd=$scheme://$http_host$escaped_request_uri
          nginx.ingress.kubernetes.io/auth-response-headers: |-
            Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-entitlements,X-authentik-email,X-authentik-name,X-authentik-uid
          nginx.ingress.kubernetes.io/auth-snippet: |
            proxy_set_header X-Forwarded-Host $http_host;
        hosts:
          - prometheus.seercle.com
        tls:
          - hosts:
              - prometheus.seercle.com
            secretName: prometheus-tls
